---
root: true
extends:
  - react-app
settings:
  react:
    version: 16.6
rules:
  block-scoped-var: error
  brace-style:
    - error
    - stroustrup
  camelcase: off
  consistent-return: error
  curly:
    - error
    - all
  comma-dangle:
    - error
    - always-multiline
  dot-notation:
    - error
    -
      allowKeywords: true
  eqeqeq:
    - error
    - allow-null
  space-before-blocks: error
  strict: off
  new-cap: error
  no-bitwise: error
  no-caller: error
  no-case-declarations: off
  no-cond-assign:
    - error
    - except-parens
  no-debugger: error
  no-empty: error
  no-eval: error
  no-extend-native: error
  no-irregular-whitespace: error
  no-iterator: error
  no-loop-func: error
  no-multi-str: error
  no-new: error
  no-proto: error
  no-script-url: error
  no-sequences: error
  no-undef: error
  no-unused-vars:
    - error
    - args: none
  no-with: error
  one-var:
    - error
    - never
  indent:
    - error
    - tab
    -
      SwitchCase: 1
  quotes:
    - error
    - single
  semi:
    - error
    - always
  valid-typeof: error
  wrap-iife:
    - error
    - inside
  array-bracket-spacing:
    - error
    - always
    -
      objectsInArrays: false
      arraysInArrays: false

  no-warning-comments: warn
  no-console: warn

  no-var: error
  arrow-spacing: error
  prefer-arrow-callback: error
  prefer-const: error
  prefer-rest-params: error
  prefer-spread: error
  prefer-template: error
  rest-spread-spacing: error
  template-curly-spacing: error

  react/button-has-type: error
  react/default-props-match-prop-types:
    - error
    -
      allowRequiredDefaults: true
  react/destructuring-assignment: error
  react/no-access-state-in-setstate: error
  react/no-array-index-key: warn
  react/no-children-prop: warn
  react/no-danger: warn
  react/no-danger-with-children: warn
  react/no-deprecated: warn
  react/no-find-dom-node: error
  react/no-multi-comp:
    - error
    -
      ignoreStateless: true
  react/no-redundant-should-component-update: error
  react/no-render-return-value: error
  react/no-typos: error
  react/no-string-refs: error
  react/no-this-in-sfc: error
  react/no-unescaped-entities: error
  react/no-unknown-property: error
  react/no-unsafe: error
  react/no-unused-prop-types: error
  react/no-unused-state: error
  react/prop-types: error
  react/self-closing-comp: error
  react/sort-comp: error
  react/void-dom-elements-no-children: error
  react/forbid-foreign-prop-types: off

  react/jsx-boolean-value: error
  react/jsx-child-element-spacing: error
  react/jsx-closing-bracket-location: error
  react/jsx-closing-tag-location: error
  react/jsx-curly-spacing:
    - error
    -
      children: true
  react/jsx-equals-spacing: error
  react/jsx-first-prop-new-line: error
  react/jsx-handler-names: error
  react/jsx-indent:
    - error
    - tab
  react/jsx-indent-props:
    - error
    - tab
  react/jsx-key: error
  react/jsx-max-props-per-line:
    - error
    -
      maximum: 3
  react/jsx-no-bind:
    - error
    -
      allowArrowFunctions: true
  react/jsx-no-comment-textnodes: error
  react/jsx-curly-brace-presence:
    - error
    - never
  react/jsx-props-no-multi-spaces: error
  react/jsx-tag-spacing:
    - error
    -
      closingSlash: never
      beforeSelfClosing: always
      afterOpening: never
      beforeClosing: never
  react/jsx-wrap-multilines:
    - error
    -
      declaration: parens
      assignment: parens
      return: parens
      arrow: parens
      condition: parens
      logical: parens
      prop: parens-new-line
